# Generated by Django 6.0.6 on 2026-06-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_sociallink_alter_about_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.URLField(max_length=100),
        ),
    ]
